Novemberbranch
brickstudymasons/brickstudy pull request #125
Opened 2024-11-01 15:56 UTC by AidaasinAyda

Hi makeda, could you check the score file? And if possible upload the csvss

2024-11-06 05:11 UTC, drcandacemakedamoore commented
The version of the script try_replace_colnames_scorecsvs.R pushed up does not accomplish it's mission. I suspect you pushed an early version. The script needs to go all the way through until you save a csv file or files which are the one you want.

2024-11-06 19:13 UTC, AidaasinAyda reviewed
@drcandacemakedamoore 
This is the new file. I wanted to create a pul request like last time, but the yellow status line with a green button didn't show up, so I'm trying to get your attention this way!

2024-11-08 10:15 UTC, brickstudymasons commented on .gitignore
This change is fine.

2024-11-08 10:16 UTC, brickstudymasons commented on brickstudy.Rproj
I'm not sure you meant to push this.

2024-11-08 10:17 UTC, brickstudymasons commented
You pushed changes on the .gitignore plus 6 new files here. I do not know if you meant me to review all 6 files. If not please open a PR with one single file, and perhaps the .gitignore changes you intend.

2024-11-08 10:18 UTC, brickstudymasons commented on r_scripts/Script_regions_most_burden_WMH_Volbrain.R
This is an important script, and should be in the repo.

2024-11-08 10:19 UTC, brickstudymasons commented on r_scripts/fs_table_marjolein_abstract_28102024.R
Again, an important script that should be in the repo somewhere probably, but I'm not sure you meant to include it.

2024-11-08 10:27 UTC, brickstudymasons commented on r_scripts/fs_table_marjolein_abstract_28102024.R
Also, you are trying to merge into main. This is incorrect @AidaasinAyda . Please make a pull request into develop with only the files you want for certain.

2024-11-08 10:29 UTC, drcandacemakedamoore requested changes
The pull request is onto main. Again...pull requests need to come off of develop, and go onto develop. I checked git log --branch, and this branch came from the main. Please make a PR from a branch off of develop, with only the files you want, then request to merge onto develop. Alternatively you can simply send me the files you want changed by email.

2024-11-23 11:55 UTC, drcandacemakedamoore commented
replaced by properly branched

2024-11-23 11:55 UTC, closed without merging